language: c
compiler:
  - gcc

before_script:
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  - sudo apt-get update -qq
  - sudo apt-get install -y python3.3

script:
  - make -C unix
  - cd tests && MICROPY_CPYTHON3=python3.3 ./run-tests
